name: Release

on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: pnpm/action-setup@v4

      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: ~/.local/share/pnpm/store/v3
          key: pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: pnpm-

      - run: pnpm install --frozen-lockfile

      - name: Create GitHub Release
        run: pnpm run gh:release
        env:
          CONVENTIONAL_GITHUB_RELEASER_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Build
        run: pnpm run build

      - name: Package VSIX
        run: pnpm exec vsce package --no-dependencies

      - name: Upload VSIX to GitHub Release
        run: gh release upload ${{github.ref_name}} *.vsix --clobber
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
